version: "3"
services:
  api:
    image: api:dev
    container_name: api
    command: bash -c "npm start"
    volumes:
      - ../../app:/home/app/api/app
      - ../../package.json:/home/app/api/package.json
      - ../../gulpfile.js:/home/app/api/gulpfile.js
      - ../../.env:/home/app/api/.env
      - ../../.env.example:/home/app/api/.env.example
      - ../../.babelrc:/home/app/api/.babelrc
      - ../../.eslintrc:/home/app/api/.eslintrc
      - ../../.eslintignore:/home/app/api/.eslintignore
      - /home/app/api/.tmp
    ports:
      - "9090:9090"
    environment:
      NODE_ENV: development
      PORT: 9090
      TZ: Asia/Seoul
    tty: true

  db: 
    image: mongo:3-jessie
    container_name: mongo
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    ports:
      - "27017:27017"

#    environment:
#      MONGODB_USER="user" 
#      MONGODB_PASS="pass"
